### ISSUE TITLE
Using Features

### ISSUE THREAD

**Issue by tanneberger** [tlm-solutions/tlms.rs#1]
To much shit in one crate use features so our clients only get what they want.

**Comment by gshipunov** [comment]
Quick suggestion on how to dice it out:
- [ ] location.rs
- [ ] Sort telegram types in different modules? So we can only build needed ones (e.g. lofi/crayon only uses savetelegram)

**Comment by tanneberger** [comment]
I would say:

- [ ] database (management)
- [ ] telegrams
- [ ] location.rs + trekkie + gps_ddvb.rs = interpolation foo

would make more sense especially if u look at the current module structure. @oxapentane

**Comment by tanneberger** [comment]
done
