### ISSUE TITLE
Bikeshedding Schema for GPS Positions

### ISSUE THREAD

**Issue by tanneberger** [tlm-solutions/tlms.rs#5]
# Problem 

We currently save all the GPS info in gpx files on the server its maybe smarter to save them in the postgres with all the other information. 

# Proposed Solution

The [Struct](https://github.com/tlm-solutions/lofi/blob/91a61d38a877530be96f8c7e9a03858de4b6a32a/src/gps.rs#L12) should be implemented as a database struct. 

```sql
CREATE TABLE gps_positions (
id BIGINT PRIMARY KEY,
trekkie_run UUID FOREIGN KEY NOT NULL, 
timestamp TIMESTAMP NOT NULL,
lat FLOAT NOT NULL,
lon FLOAT NOT NULL,
elevation FLOAT
verical_accuracy FLOAT,
bearing FLOAT,
speed FLOAT
);
```

**Comment by gshipunov** [comment]
implemented by https://github.com/tlm-solutions/tlms.rs/pull/9
